name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker
        run: |
          docker build -t hello-app .
          docker run -d -p 5000:5000 hello-app  # Runs the container

      - name: Run Tests (Dummy Test)
        run: echo "Tests passed!"

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@0.1.2-beta
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "production"  # Replace this with your actual service name
